#pragma once

#define CONFIG_USB_PRINTF(...) do { } while (0)
#define CONFIG_USB_DBG_LEVEL USB_DBG_ERROR
#define CONFIG_USB_ALIGN_SIZE 4
#define USB_NOCACHE_RAM_SECTION
#define CONFIG_USB_MEMCPY_DISABLE
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 256
#define CONFIG_USBDEV_ADVANCE_DESC
#define CONFIG_USBDEV_MAX_BUS 1
