#pragma once

/* Applied to the UART peripheral baud rate after CDC line coding. */
#ifndef UART_BRIDGE_BAUD_ADJUST_PPM
#define UART_BRIDGE_BAUD_ADJUST_PPM 0
#endif

/*
 * Per-port ESP automatic-download control.  When enabled, the USB CDC DTR
 * and RTS control-line states drive BOOT/GPIO0 and EN respectively.  Both
 * signals are active low at the ESP pins.
 */
#ifndef UART_BRIDGE_PORT0_ESP_AUTO_RESET
#define UART_BRIDGE_PORT0_ESP_AUTO_RESET 1
#endif

#ifndef UART_BRIDGE_PORT1_ESP_AUTO_RESET
#define UART_BRIDGE_PORT1_ESP_AUTO_RESET 1
#endif

#if UART_BRIDGE_PORT0_ESP_AUTO_RESET
#define UART_BRIDGE_PORT0_ESP_BOOT_GPIO GPIOA
#define UART_BRIDGE_PORT0_ESP_BOOT_PIN GPIO_Pin_0
#define UART_BRIDGE_PORT0_ESP_BOOT_GPIO_CLOCK RCC_APB2Periph_GPIOA
#define UART_BRIDGE_PORT0_ESP_EN_GPIO GPIOA
#define UART_BRIDGE_PORT0_ESP_EN_PIN GPIO_Pin_1
#define UART_BRIDGE_PORT0_ESP_EN_GPIO_CLOCK RCC_APB2Periph_GPIOA
#endif

#if UART_BRIDGE_PORT1_ESP_AUTO_RESET
#define UART_BRIDGE_PORT1_ESP_BOOT_GPIO GPIOB
#define UART_BRIDGE_PORT1_ESP_BOOT_PIN GPIO_Pin_0
#define UART_BRIDGE_PORT1_ESP_BOOT_GPIO_CLOCK RCC_APB2Periph_GPIOB
#define UART_BRIDGE_PORT1_ESP_EN_GPIO GPIOB
#define UART_BRIDGE_PORT1_ESP_EN_PIN GPIO_Pin_1
#define UART_BRIDGE_PORT1_ESP_EN_GPIO_CLOCK RCC_APB2Periph_GPIOB
#endif
